// Code generated by MockGen. DO NOT EDIT.
// Source: execute.go

// Package ops is a generated GoMock package.
package ops

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExecute is a mock of Execute interface.
type MockExecute struct {
	ctrl     *gomock.Controller
	recorder *MockExecuteMockRecorder
}

// MockExecuteMockRecorder is the mock recorder for MockExecute.
type MockExecuteMockRecorder struct {
	mock *MockExecute
}

// NewMockExecute creates a new mock instance.
func NewMockExecute(ctrl *gomock.Controller) *MockExecute {
	mock := &MockExecute{ctrl: ctrl}
	mock.recorder = &MockExecuteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecute) EXPECT() *MockExecuteMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecute) Execute(command string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Execute", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockExecuteMockRecorder) Execute(command interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecute)(nil).Execute), varargs...)
}
