// Code generated by MockGen. DO NOT EDIT.
// Source: ops.go

// Package ops is a generated GoMock package.
package ops

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockOps is a mock of Ops interface
type MockOps struct {
	ctrl     *gomock.Controller
	recorder *MockOpsMockRecorder
}

// MockOpsMockRecorder is the mock recorder for MockOps
type MockOpsMockRecorder struct {
	mock *MockOps
}

// NewMockOps creates a new mock instance
func NewMockOps(ctrl *gomock.Controller) *MockOps {
	mock := &MockOps{ctrl: ctrl}
	mock.recorder = &MockOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOps) EXPECT() *MockOpsMockRecorder {
	return m.recorder
}

// SystemctlAction mocks base method
func (m *MockOps) SystemctlAction(action string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{action}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SystemctlAction", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemctlAction indicates an expected call of SystemctlAction
func (mr *MockOpsMockRecorder) SystemctlAction(action interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{action}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemctlAction", reflect.TypeOf((*MockOps)(nil).SystemctlAction), varargs...)
}

// RunInHostNamespace mocks base method
func (m *MockOps) RunInHostNamespace(command string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunInHostNamespace", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunInHostNamespace indicates an expected call of RunInHostNamespace
func (mr *MockOpsMockRecorder) RunInHostNamespace(command interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInHostNamespace", reflect.TypeOf((*MockOps)(nil).RunInHostNamespace), varargs...)
}

// RunBashInHostNamespace mocks base method
func (m *MockOps) RunBashInHostNamespace(command string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunBashInHostNamespace", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunBashInHostNamespace indicates an expected call of RunBashInHostNamespace
func (mr *MockOpsMockRecorder) RunBashInHostNamespace(command interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBashInHostNamespace", reflect.TypeOf((*MockOps)(nil).RunBashInHostNamespace), varargs...)
}

// RunUnauthenticatedEtcdServer mocks base method
func (m *MockOps) RunUnauthenticatedEtcdServer(authFile, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunUnauthenticatedEtcdServer", authFile, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunUnauthenticatedEtcdServer indicates an expected call of RunUnauthenticatedEtcdServer
func (mr *MockOpsMockRecorder) RunUnauthenticatedEtcdServer(authFile, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunUnauthenticatedEtcdServer", reflect.TypeOf((*MockOps)(nil).RunUnauthenticatedEtcdServer), authFile, name)
}

// GetImageFromPodDefinition mocks base method
func (m *MockOps) GetImageFromPodDefinition(etcdStaticPodFile, containerImage string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageFromPodDefinition", etcdStaticPodFile, containerImage)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageFromPodDefinition indicates an expected call of GetImageFromPodDefinition
func (mr *MockOpsMockRecorder) GetImageFromPodDefinition(etcdStaticPodFile, containerImage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageFromPodDefinition", reflect.TypeOf((*MockOps)(nil).GetImageFromPodDefinition), etcdStaticPodFile, containerImage)
}

// RunRecert mocks base method
func (m *MockOps) RunRecert(recertContainerImage, authFile, recertConfigFile string, additionalPodmanParams ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{recertContainerImage, authFile, recertConfigFile}
	for _, a := range additionalPodmanParams {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunRecert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunRecert indicates an expected call of RunRecert
func (mr *MockOpsMockRecorder) RunRecert(recertContainerImage, authFile, recertConfigFile interface{}, additionalPodmanParams ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{recertContainerImage, authFile, recertConfigFile}, additionalPodmanParams...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRecert", reflect.TypeOf((*MockOps)(nil).RunRecert), varargs...)
}
