# Due to a limitation in Mintmaker, we need to create a dummy Dockerfile that does not use ARGs
# This should match the RUNTIME_IMAGE in container_build_args.conf
# Mintmaker should keep these in sync automatically when it performs updates
FROM registry.redhat.io/ubi9/ubi-minimal-pqc:latest@sha256:b280df203f9ec5d03439ae79cc3f26a01dc04f01c9259853398be438a334ade2
#
