version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - depguard
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    gocritic:
      enabled-checks:
        # Diagnostic (non-default)
        - commentedOutCode
        - nilValReturn
        - weakCond
        - octalLiteral
        - sloppyReassign
        # Performance (non-default)
        - equalFold
        - indexAlloc
        - rangeExprCopy
        - appendCombine
        # Style (non-default)
        - boolExprSimplify
        - commentedOutImport
        - docStub
        - emptyFallthrough
        - emptyStringTest
        - hexLiteral
        - methodExprCall
        - stringXbytes
        - typeAssertChain
        - unlabelStmt
        - yodaStyleExpr
        # Opinionated (non-default)
        - initClause
        - nestingReduce
        - ptrToRefParam
        - typeUnparen
        - unnecessaryBlock
        - paramTypeCombine
    staticcheck:
      checks:
        - "all"
        - "-ST*"
        - "-QF*"
        - "-S*"
    revive:
      rules:
        - name: if-return
          severity: warning
          disabled: true
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: warning
          disabled: false
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .WrapPrefixf(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - _test\.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
