---
extends: default
ignore:
  - .konflux/catalog/catalog-template.out.yaml  # This is generated for Konflux builds
  - .konflux/catalog/lifecycle-agent/catalog.yaml  # This is generated for Konflux builds
  - .konflux/lock-runtime/rpms.lock.yaml  # These are generated files so linting them is problematic
  - bin/
  - bundle/  # These are generated files so linting them is problematic
  - config/  # These are generated files so linting them is problematic
  - git/
  - telco5g-konflux/
  - testbin/
  - vendor/
rules:
  line-length: disable
