// Code generated by MockGen. DO NOT EDIT.
// Source: ../clusterconfig.go
//
// Generated by this command:
//
//	mockgen -source ../clusterconfig.go -destination mock_clusterconfig.go -write_generate_directive
//
// Package mock_clusterconfig is a generated GoMock package.
package mock_clusterconfig

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -source ../clusterconfig.go -destination mock_clusterconfig.go -write_generate_directive

// MockUpgradeClusterConfigGatherer is a mock of UpgradeClusterConfigGatherer interface.
type MockUpgradeClusterConfigGatherer struct {
	ctrl     *gomock.Controller
	recorder *MockUpgradeClusterConfigGathererMockRecorder
}

// MockUpgradeClusterConfigGathererMockRecorder is the mock recorder for MockUpgradeClusterConfigGatherer.
type MockUpgradeClusterConfigGathererMockRecorder struct {
	mock *MockUpgradeClusterConfigGatherer
}

// NewMockUpgradeClusterConfigGatherer creates a new mock instance.
func NewMockUpgradeClusterConfigGatherer(ctrl *gomock.Controller) *MockUpgradeClusterConfigGatherer {
	mock := &MockUpgradeClusterConfigGatherer{ctrl: ctrl}
	mock.recorder = &MockUpgradeClusterConfigGathererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpgradeClusterConfigGatherer) EXPECT() *MockUpgradeClusterConfigGathererMockRecorder {
	return m.recorder
}

// FetchClusterConfig mocks base method.
func (m *MockUpgradeClusterConfigGatherer) FetchClusterConfig(ctx context.Context, ostreeDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchClusterConfig", ctx, ostreeDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchClusterConfig indicates an expected call of FetchClusterConfig.
func (mr *MockUpgradeClusterConfigGathererMockRecorder) FetchClusterConfig(ctx, ostreeDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchClusterConfig", reflect.TypeOf((*MockUpgradeClusterConfigGatherer)(nil).FetchClusterConfig), ctx, ostreeDir)
}

// FetchLvmConfig mocks base method.
func (m *MockUpgradeClusterConfigGatherer) FetchLvmConfig(ctx context.Context, ostreeDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLvmConfig", ctx, ostreeDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchLvmConfig indicates an expected call of FetchLvmConfig.
func (mr *MockUpgradeClusterConfigGathererMockRecorder) FetchLvmConfig(ctx, ostreeDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLvmConfig", reflect.TypeOf((*MockUpgradeClusterConfigGatherer)(nil).FetchLvmConfig), ctx, ostreeDir)
}
