// Code generated by MockGen. DO NOT EDIT.
// Source: ipc_config_handlers.go
//
// Generated by this command:
//
//	mockgen -source=ipc_config_handlers.go -package=controllers -destination=ipc_config_handlers_mock.go
//
// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	logr "github.com/go-logr/logr"
	v1 "github.com/openshift-kni/lifecycle-agent/api/ipconfig/v1"
	gomock "go.uber.org/mock/gomock"
	controllerruntime "sigs.k8s.io/controller-runtime"
)

// MockIPConfigConfigPhasesHandlerInterface is a mock of IPConfigConfigPhasesHandlerInterface interface.
type MockIPConfigConfigPhasesHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIPConfigConfigPhasesHandlerInterfaceMockRecorder
}

// MockIPConfigConfigPhasesHandlerInterfaceMockRecorder is the mock recorder for MockIPConfigConfigPhasesHandlerInterface.
type MockIPConfigConfigPhasesHandlerInterfaceMockRecorder struct {
	mock *MockIPConfigConfigPhasesHandlerInterface
}

// NewMockIPConfigConfigPhasesHandlerInterface creates a new mock instance.
func NewMockIPConfigConfigPhasesHandlerInterface(ctrl *gomock.Controller) *MockIPConfigConfigPhasesHandlerInterface {
	mock := &MockIPConfigConfigPhasesHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockIPConfigConfigPhasesHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPConfigConfigPhasesHandlerInterface) EXPECT() *MockIPConfigConfigPhasesHandlerInterfaceMockRecorder {
	return m.recorder
}

// PostConfiguration mocks base method.
func (m *MockIPConfigConfigPhasesHandlerInterface) PostConfiguration(ctx context.Context, ipc *v1.IPConfig, logger logr.Logger) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostConfiguration", ctx, ipc, logger)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostConfiguration indicates an expected call of PostConfiguration.
func (mr *MockIPConfigConfigPhasesHandlerInterfaceMockRecorder) PostConfiguration(ctx, ipc, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostConfiguration", reflect.TypeOf((*MockIPConfigConfigPhasesHandlerInterface)(nil).PostConfiguration), ctx, ipc, logger)
}

// PreConfiguration mocks base method.
func (m *MockIPConfigConfigPhasesHandlerInterface) PreConfiguration(ctx context.Context, ipc *v1.IPConfig, logger logr.Logger) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreConfiguration", ctx, ipc, logger)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreConfiguration indicates an expected call of PreConfiguration.
func (mr *MockIPConfigConfigPhasesHandlerInterfaceMockRecorder) PreConfiguration(ctx, ipc, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreConfiguration", reflect.TypeOf((*MockIPConfigConfigPhasesHandlerInterface)(nil).PreConfiguration), ctx, ipc, logger)
}

// PrePivot mocks base method.
func (m *MockIPConfigConfigPhasesHandlerInterface) PrePivot(ctx context.Context, ipc *v1.IPConfig, logger logr.Logger) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrePivot", ctx, ipc, logger)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrePivot indicates an expected call of PrePivot.
func (mr *MockIPConfigConfigPhasesHandlerInterfaceMockRecorder) PrePivot(ctx, ipc, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrePivot", reflect.TypeOf((*MockIPConfigConfigPhasesHandlerInterface)(nil).PrePivot), ctx, ipc, logger)
}
