// Code generated by MockGen. DO NOT EDIT.
// Source: ipc_rollback_handlers.go
//
// Generated by this command:
//
//	mockgen -source=ipc_rollback_handlers.go -package=controllers -destination=ipc_rollback_handlers_mock.go
//
// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	logr "github.com/go-logr/logr"
	v1 "github.com/openshift-kni/lifecycle-agent/api/ipconfig/v1"
	gomock "go.uber.org/mock/gomock"
	controllerruntime "sigs.k8s.io/controller-runtime"
)

// MockIPConfigRollbackPhasesHandlerInterface is a mock of IPConfigRollbackPhasesHandlerInterface interface.
type MockIPConfigRollbackPhasesHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIPConfigRollbackPhasesHandlerInterfaceMockRecorder
}

// MockIPConfigRollbackPhasesHandlerInterfaceMockRecorder is the mock recorder for MockIPConfigRollbackPhasesHandlerInterface.
type MockIPConfigRollbackPhasesHandlerInterfaceMockRecorder struct {
	mock *MockIPConfigRollbackPhasesHandlerInterface
}

// NewMockIPConfigRollbackPhasesHandlerInterface creates a new mock instance.
func NewMockIPConfigRollbackPhasesHandlerInterface(ctrl *gomock.Controller) *MockIPConfigRollbackPhasesHandlerInterface {
	mock := &MockIPConfigRollbackPhasesHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockIPConfigRollbackPhasesHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPConfigRollbackPhasesHandlerInterface) EXPECT() *MockIPConfigRollbackPhasesHandlerInterfaceMockRecorder {
	return m.recorder
}

// PostPivot mocks base method.
func (m *MockIPConfigRollbackPhasesHandlerInterface) PostPivot(ctx context.Context, ipc *v1.IPConfig, logger logr.Logger) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostPivot", ctx, ipc, logger)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostPivot indicates an expected call of PostPivot.
func (mr *MockIPConfigRollbackPhasesHandlerInterfaceMockRecorder) PostPivot(ctx, ipc, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostPivot", reflect.TypeOf((*MockIPConfigRollbackPhasesHandlerInterface)(nil).PostPivot), ctx, ipc, logger)
}

// PrePivot mocks base method.
func (m *MockIPConfigRollbackPhasesHandlerInterface) PrePivot(ctx context.Context, ipc *v1.IPConfig, logger logr.Logger) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrePivot", ctx, ipc, logger)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrePivot indicates an expected call of PrePivot.
func (mr *MockIPConfigRollbackPhasesHandlerInterfaceMockRecorder) PrePivot(ctx, ipc, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrePivot", reflect.TypeOf((*MockIPConfigRollbackPhasesHandlerInterface)(nil).PrePivot), ctx, ipc, logger)
}
