// Code generated by MockGen. DO NOT EDIT.
// Source: ops.go
//
// Generated by this command:
//
//	mockgen -source=ops.go -package=ops -destination=mock_ops.go
//
// Package ops is a generated GoMock package.
package ops

import (
	context "context"
	os "os"
	reflect "reflect"

	logrus "github.com/sirupsen/logrus"
	gomock "go.uber.org/mock/gomock"
)

// MockOps is a mock of Ops interface.
type MockOps struct {
	ctrl     *gomock.Controller
	recorder *MockOpsMockRecorder
}

// MockOpsMockRecorder is the mock recorder for MockOps.
type MockOpsMockRecorder struct {
	mock *MockOps
}

// NewMockOps creates a new mock instance.
func NewMockOps(ctrl *gomock.Controller) *MockOps {
	mock := &MockOps{ctrl: ctrl}
	mock.recorder = &MockOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOps) EXPECT() *MockOpsMockRecorder {
	return m.recorder
}

// Chroot mocks base method.
func (m *MockOps) Chroot(chrootPath string) (func() error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chroot", chrootPath)
	ret0, _ := ret[0].(func() error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chroot indicates an expected call of Chroot.
func (mr *MockOpsMockRecorder) Chroot(chrootPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chroot", reflect.TypeOf((*MockOps)(nil).Chroot), chrootPath)
}

// CopyFile mocks base method.
func (m *MockOps) CopyFile(src, dest string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", src, dest, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockOpsMockRecorder) CopyFile(src, dest, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockOps)(nil).CopyFile), src, dest, perm)
}

// CreateExtraPartition mocks base method.
func (m *MockOps) CreateExtraPartition(ctx context.Context, installationDisk, extraPartitionLabel, extraPartitionStart string, extraPartitionNumber uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExtraPartition", ctx, installationDisk, extraPartitionLabel, extraPartitionStart, extraPartitionNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExtraPartition indicates an expected call of CreateExtraPartition.
func (mr *MockOpsMockRecorder) CreateExtraPartition(ctx, installationDisk, extraPartitionLabel, extraPartitionStart, extraPartitionNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExtraPartition", reflect.TypeOf((*MockOps)(nil).CreateExtraPartition), ctx, installationDisk, extraPartitionLabel, extraPartitionStart, extraPartitionNumber)
}

// CreateIsoWithEmbeddedIgnition mocks base method.
func (m *MockOps) CreateIsoWithEmbeddedIgnition(log logrus.FieldLogger, ignitionBytes []byte, baseIsoPath, outputIsoPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIsoWithEmbeddedIgnition", log, ignitionBytes, baseIsoPath, outputIsoPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIsoWithEmbeddedIgnition indicates an expected call of CreateIsoWithEmbeddedIgnition.
func (mr *MockOpsMockRecorder) CreateIsoWithEmbeddedIgnition(log, ignitionBytes, baseIsoPath, outputIsoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIsoWithEmbeddedIgnition", reflect.TypeOf((*MockOps)(nil).CreateIsoWithEmbeddedIgnition), log, ignitionBytes, baseIsoPath, outputIsoPath)
}

// EnableClusterServices mocks base method.
func (m *MockOps) EnableClusterServices(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableClusterServices", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableClusterServices indicates an expected call of EnableClusterServices.
func (mr *MockOpsMockRecorder) EnableClusterServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableClusterServices", reflect.TypeOf((*MockOps)(nil).EnableClusterServices), ctx)
}

// ExtractTarWithSELinux mocks base method.
func (m *MockOps) ExtractTarWithSELinux(ctx context.Context, srcPath, destPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractTarWithSELinux", ctx, srcPath, destPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtractTarWithSELinux indicates an expected call of ExtractTarWithSELinux.
func (mr *MockOpsMockRecorder) ExtractTarWithSELinux(ctx, srcPath, destPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractTarWithSELinux", reflect.TypeOf((*MockOps)(nil).ExtractTarWithSELinux), ctx, srcPath, destPath)
}

// ForceExpireSeedCrypto mocks base method.
func (m *MockOps) ForceExpireSeedCrypto(ctx context.Context, recertContainerImage, authFile string, hasKubeAdminPassword bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceExpireSeedCrypto", ctx, recertContainerImage, authFile, hasKubeAdminPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceExpireSeedCrypto indicates an expected call of ForceExpireSeedCrypto.
func (mr *MockOpsMockRecorder) ForceExpireSeedCrypto(ctx, recertContainerImage, authFile, hasKubeAdminPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceExpireSeedCrypto", reflect.TypeOf((*MockOps)(nil).ForceExpireSeedCrypto), ctx, recertContainerImage, authFile, hasKubeAdminPassword)
}

// GetContainerStorageTarget mocks base method.
func (m *MockOps) GetContainerStorageTarget(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerStorageTarget", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerStorageTarget indicates an expected call of GetContainerStorageTarget.
func (mr *MockOpsMockRecorder) GetContainerStorageTarget(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerStorageTarget", reflect.TypeOf((*MockOps)(nil).GetContainerStorageTarget), ctx)
}

// GetHostname mocks base method.
func (m *MockOps) GetHostname() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostname")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostname indicates an expected call of GetHostname.
func (mr *MockOpsMockRecorder) GetHostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostname", reflect.TypeOf((*MockOps)(nil).GetHostname))
}

// ImageExists mocks base method.
func (m *MockOps) ImageExists(ctx context.Context, img string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageExists", ctx, img)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageExists indicates an expected call of ImageExists.
func (mr *MockOpsMockRecorder) ImageExists(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageExists", reflect.TypeOf((*MockOps)(nil).ImageExists), ctx, img)
}

// IsImageMounted mocks base method.
func (m *MockOps) IsImageMounted(ctx context.Context, img string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsImageMounted", ctx, img)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsImageMounted indicates an expected call of IsImageMounted.
func (mr *MockOpsMockRecorder) IsImageMounted(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsImageMounted", reflect.TypeOf((*MockOps)(nil).IsImageMounted), ctx, img)
}

// IsNotExist mocks base method.
func (m *MockOps) IsNotExist(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNotExist", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNotExist indicates an expected call of IsNotExist.
func (mr *MockOpsMockRecorder) IsNotExist(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNotExist", reflect.TypeOf((*MockOps)(nil).IsNotExist), err)
}

// ListBlockDevices mocks base method.
func (m *MockOps) ListBlockDevices(ctx context.Context) ([]BlockDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlockDevices", ctx)
	ret0, _ := ret[0].([]BlockDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockDevices indicates an expected call of ListBlockDevices.
func (mr *MockOpsMockRecorder) ListBlockDevices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockDevices", reflect.TypeOf((*MockOps)(nil).ListBlockDevices), ctx)
}

// MkdirAll mocks base method.
func (m *MockOps) MkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockOpsMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockOps)(nil).MkdirAll), path, perm)
}

// Mount mocks base method.
func (m *MockOps) Mount(ctx context.Context, deviceName, mountFolder string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mount", ctx, deviceName, mountFolder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mount indicates an expected call of Mount.
func (mr *MockOpsMockRecorder) Mount(ctx, deviceName, mountFolder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mount", reflect.TypeOf((*MockOps)(nil).Mount), ctx, deviceName, mountFolder)
}

// MountImage mocks base method.
func (m *MockOps) MountImage(ctx context.Context, img string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MountImage", ctx, img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MountImage indicates an expected call of MountImage.
func (mr *MockOpsMockRecorder) MountImage(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MountImage", reflect.TypeOf((*MockOps)(nil).MountImage), ctx, img)
}

// ReadDir mocks base method.
func (m *MockOps) ReadDir(path string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", path)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockOpsMockRecorder) ReadDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockOps)(nil).ReadDir), path)
}

// ReadFile mocks base method.
func (m *MockOps) ReadFile(filename string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", filename)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockOpsMockRecorder) ReadFile(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockOps)(nil).ReadFile), filename)
}

// RecertFullFlow mocks base method.
func (m *MockOps) RecertFullFlow(ctx context.Context, recertContainerImage, authFile, configFile string, preRecertOperations, postRecertOperations func() error, additionalPodmanParams ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, recertContainerImage, authFile, configFile, preRecertOperations, postRecertOperations}
	for _, a := range additionalPodmanParams {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RecertFullFlow", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecertFullFlow indicates an expected call of RecertFullFlow.
func (mr *MockOpsMockRecorder) RecertFullFlow(ctx, recertContainerImage, authFile, configFile, preRecertOperations, postRecertOperations any, additionalPodmanParams ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, recertContainerImage, authFile, configFile, preRecertOperations, postRecertOperations}, additionalPodmanParams...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecertFullFlow", reflect.TypeOf((*MockOps)(nil).RecertFullFlow), varargs...)
}

// RemountBoot mocks base method.
func (m *MockOps) RemountBoot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemountBoot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemountBoot indicates an expected call of RemountBoot.
func (mr *MockOpsMockRecorder) RemountBoot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemountBoot", reflect.TypeOf((*MockOps)(nil).RemountBoot), ctx)
}

// RemountSysroot mocks base method.
func (m *MockOps) RemountSysroot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemountSysroot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemountSysroot indicates an expected call of RemountSysroot.
func (mr *MockOpsMockRecorder) RemountSysroot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemountSysroot", reflect.TypeOf((*MockOps)(nil).RemountSysroot), ctx)
}

// RemoveAllFiles mocks base method.
func (m *MockOps) RemoveAllFiles(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllFiles", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllFiles indicates an expected call of RemoveAllFiles.
func (mr *MockOpsMockRecorder) RemoveAllFiles(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllFiles", reflect.TypeOf((*MockOps)(nil).RemoveAllFiles), path)
}

// RemoveFile mocks base method.
func (m *MockOps) RemoveFile(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockOpsMockRecorder) RemoveFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockOps)(nil).RemoveFile), path)
}

// RestoreOriginalSeedCrypto mocks base method.
func (m *MockOps) RestoreOriginalSeedCrypto(ctx context.Context, recertContainerImage, authFile string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreOriginalSeedCrypto", ctx, recertContainerImage, authFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreOriginalSeedCrypto indicates an expected call of RestoreOriginalSeedCrypto.
func (mr *MockOpsMockRecorder) RestoreOriginalSeedCrypto(ctx, recertContainerImage, authFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreOriginalSeedCrypto", reflect.TypeOf((*MockOps)(nil).RestoreOriginalSeedCrypto), ctx, recertContainerImage, authFile)
}

// RunBashInHostNamespace mocks base method.
func (m *MockOps) RunBashInHostNamespace(ctx context.Context, command string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunBashInHostNamespace", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunBashInHostNamespace indicates an expected call of RunBashInHostNamespace.
func (mr *MockOpsMockRecorder) RunBashInHostNamespace(ctx, command any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBashInHostNamespace", reflect.TypeOf((*MockOps)(nil).RunBashInHostNamespace), varargs...)
}

// RunInHostNamespace mocks base method.
func (m *MockOps) RunInHostNamespace(ctx context.Context, command string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunInHostNamespace", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunInHostNamespace indicates an expected call of RunInHostNamespace.
func (mr *MockOpsMockRecorder) RunInHostNamespace(ctx, command any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInHostNamespace", reflect.TypeOf((*MockOps)(nil).RunInHostNamespace), varargs...)
}

// RunListOfCommands mocks base method.
func (m *MockOps) RunListOfCommands(ctx context.Context, cmds []*CMD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunListOfCommands", ctx, cmds)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunListOfCommands indicates an expected call of RunListOfCommands.
func (mr *MockOpsMockRecorder) RunListOfCommands(ctx, cmds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunListOfCommands", reflect.TypeOf((*MockOps)(nil).RunListOfCommands), ctx, cmds)
}

// RunRecert mocks base method.
func (m *MockOps) RunRecert(ctx context.Context, recertContainerImage, authFile, recertConfigFile string, additionalPodmanParams ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, recertContainerImage, authFile, recertConfigFile}
	for _, a := range additionalPodmanParams {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunRecert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunRecert indicates an expected call of RunRecert.
func (mr *MockOpsMockRecorder) RunRecert(ctx, recertContainerImage, authFile, recertConfigFile any, additionalPodmanParams ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, recertContainerImage, authFile, recertConfigFile}, additionalPodmanParams...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRecert", reflect.TypeOf((*MockOps)(nil).RunRecert), varargs...)
}

// RunSystemdAction mocks base method.
func (m *MockOps) RunSystemdAction(ctx context.Context, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunSystemdAction", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunSystemdAction indicates an expected call of RunSystemdAction.
func (mr *MockOpsMockRecorder) RunSystemdAction(ctx any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSystemdAction", reflect.TypeOf((*MockOps)(nil).RunSystemdAction), varargs...)
}

// RunUnauthenticatedEtcdServer mocks base method.
func (m *MockOps) RunUnauthenticatedEtcdServer(ctx context.Context, authFile, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunUnauthenticatedEtcdServer", ctx, authFile, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunUnauthenticatedEtcdServer indicates an expected call of RunUnauthenticatedEtcdServer.
func (mr *MockOpsMockRecorder) RunUnauthenticatedEtcdServer(ctx, authFile, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunUnauthenticatedEtcdServer", reflect.TypeOf((*MockOps)(nil).RunUnauthenticatedEtcdServer), ctx, authFile, name)
}

// SetupContainersFolderCommands mocks base method.
func (m *MockOps) SetupContainersFolderCommands(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupContainersFolderCommands", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupContainersFolderCommands indicates an expected call of SetupContainersFolderCommands.
func (mr *MockOpsMockRecorder) SetupContainersFolderCommands(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupContainersFolderCommands", reflect.TypeOf((*MockOps)(nil).SetupContainersFolderCommands), ctx)
}

// StatFile mocks base method.
func (m *MockOps) StatFile(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatFile", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatFile indicates an expected call of StatFile.
func (mr *MockOpsMockRecorder) StatFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatFile", reflect.TypeOf((*MockOps)(nil).StatFile), name)
}

// StopClusterServices mocks base method.
func (m *MockOps) StopClusterServices(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopClusterServices", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopClusterServices indicates an expected call of StopClusterServices.
func (mr *MockOpsMockRecorder) StopClusterServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopClusterServices", reflect.TypeOf((*MockOps)(nil).StopClusterServices), ctx)
}

// StopEtcdServer mocks base method.
func (m *MockOps) StopEtcdServer(ctx context.Context, authfile, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopEtcdServer", ctx, authfile, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopEtcdServer indicates an expected call of StopEtcdServer.
func (mr *MockOpsMockRecorder) StopEtcdServer(ctx, authfile, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopEtcdServer", reflect.TypeOf((*MockOps)(nil).StopEtcdServer), ctx, authfile, name)
}

// SystemctlAction mocks base method.
func (m *MockOps) SystemctlAction(ctx context.Context, action string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, action}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SystemctlAction", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemctlAction indicates an expected call of SystemctlAction.
func (mr *MockOpsMockRecorder) SystemctlAction(ctx, action any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, action}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemctlAction", reflect.TypeOf((*MockOps)(nil).SystemctlAction), varargs...)
}

// Umount mocks base method.
func (m *MockOps) Umount(ctx context.Context, deviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Umount", ctx, deviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Umount indicates an expected call of Umount.
func (mr *MockOpsMockRecorder) Umount(ctx, deviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Umount", reflect.TypeOf((*MockOps)(nil).Umount), ctx, deviceName)
}

// UnmountAndRemoveImage mocks base method.
func (m *MockOps) UnmountAndRemoveImage(ctx context.Context, img string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmountAndRemoveImage", ctx, img)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmountAndRemoveImage indicates an expected call of UnmountAndRemoveImage.
func (mr *MockOpsMockRecorder) UnmountAndRemoveImage(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmountAndRemoveImage", reflect.TypeOf((*MockOps)(nil).UnmountAndRemoveImage), ctx, img)
}

// WriteFile mocks base method.
func (m *MockOps) WriteFile(filename string, data []byte, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", filename, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockOpsMockRecorder) WriteFile(filename, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockOps)(nil).WriteFile), filename, data, perm)
}

// waitForEtcd mocks base method.
func (m *MockOps) waitForEtcd(ctx context.Context, healthzEndpoint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "waitForEtcd", ctx, healthzEndpoint)
	ret0, _ := ret[0].(error)
	return ret0
}

// waitForEtcd indicates an expected call of waitForEtcd.
func (mr *MockOpsMockRecorder) waitForEtcd(ctx, healthzEndpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "waitForEtcd", reflect.TypeOf((*MockOps)(nil).waitForEtcd), ctx, healthzEndpoint)
}
