// Code generated by MockGen. DO NOT EDIT.
// Source: ops.go
//
// Generated by this command:
//
//	mockgen -source=ops.go -package=ops -destination=mock_ops.go
//
// Package ops is a generated GoMock package.
package ops

import (
	os "os"
	reflect "reflect"

	logrus "github.com/sirupsen/logrus"
	gomock "go.uber.org/mock/gomock"
)

// MockOps is a mock of Ops interface.
type MockOps struct {
	ctrl     *gomock.Controller
	recorder *MockOpsMockRecorder
}

// MockOpsMockRecorder is the mock recorder for MockOps.
type MockOpsMockRecorder struct {
	mock *MockOps
}

// NewMockOps creates a new mock instance.
func NewMockOps(ctrl *gomock.Controller) *MockOps {
	mock := &MockOps{ctrl: ctrl}
	mock.recorder = &MockOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOps) EXPECT() *MockOpsMockRecorder {
	return m.recorder
}

// Chroot mocks base method.
func (m *MockOps) Chroot(chrootPath string) (func() error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chroot", chrootPath)
	ret0, _ := ret[0].(func() error)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chroot indicates an expected call of Chroot.
func (mr *MockOpsMockRecorder) Chroot(chrootPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chroot", reflect.TypeOf((*MockOps)(nil).Chroot), chrootPath)
}

// CopyFile mocks base method.
func (m *MockOps) CopyFile(src, dest string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", src, dest, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockOpsMockRecorder) CopyFile(src, dest, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockOps)(nil).CopyFile), src, dest, perm)
}

// CreateExtraPartition mocks base method.
func (m *MockOps) CreateExtraPartition(installationDisk, extraPartitionLabel, extraPartitionStart string, extraPartitionNumber uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExtraPartition", installationDisk, extraPartitionLabel, extraPartitionStart, extraPartitionNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExtraPartition indicates an expected call of CreateExtraPartition.
func (mr *MockOpsMockRecorder) CreateExtraPartition(installationDisk, extraPartitionLabel, extraPartitionStart, extraPartitionNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExtraPartition", reflect.TypeOf((*MockOps)(nil).CreateExtraPartition), installationDisk, extraPartitionLabel, extraPartitionStart, extraPartitionNumber)
}

// CreateIsoWithEmbeddedIgnition mocks base method.
func (m *MockOps) CreateIsoWithEmbeddedIgnition(log logrus.FieldLogger, ignitionBytes []byte, baseIsoPath, outputIsoPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIsoWithEmbeddedIgnition", log, ignitionBytes, baseIsoPath, outputIsoPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIsoWithEmbeddedIgnition indicates an expected call of CreateIsoWithEmbeddedIgnition.
func (mr *MockOpsMockRecorder) CreateIsoWithEmbeddedIgnition(log, ignitionBytes, baseIsoPath, outputIsoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIsoWithEmbeddedIgnition", reflect.TypeOf((*MockOps)(nil).CreateIsoWithEmbeddedIgnition), log, ignitionBytes, baseIsoPath, outputIsoPath)
}

// EnableClusterServices mocks base method.
func (m *MockOps) EnableClusterServices() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableClusterServices")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableClusterServices indicates an expected call of EnableClusterServices.
func (mr *MockOpsMockRecorder) EnableClusterServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableClusterServices", reflect.TypeOf((*MockOps)(nil).EnableClusterServices))
}

// ExtractTarWithSELinux mocks base method.
func (m *MockOps) ExtractTarWithSELinux(srcPath, destPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractTarWithSELinux", srcPath, destPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtractTarWithSELinux indicates an expected call of ExtractTarWithSELinux.
func (mr *MockOpsMockRecorder) ExtractTarWithSELinux(srcPath, destPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractTarWithSELinux", reflect.TypeOf((*MockOps)(nil).ExtractTarWithSELinux), srcPath, destPath)
}

// ForceExpireSeedCrypto mocks base method.
func (m *MockOps) ForceExpireSeedCrypto(recertContainerImage, authFile string, hasKubeAdminPassword bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceExpireSeedCrypto", recertContainerImage, authFile, hasKubeAdminPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceExpireSeedCrypto indicates an expected call of ForceExpireSeedCrypto.
func (mr *MockOpsMockRecorder) ForceExpireSeedCrypto(recertContainerImage, authFile, hasKubeAdminPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceExpireSeedCrypto", reflect.TypeOf((*MockOps)(nil).ForceExpireSeedCrypto), recertContainerImage, authFile, hasKubeAdminPassword)
}

// GetContainerStorageTarget mocks base method.
func (m *MockOps) GetContainerStorageTarget() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerStorageTarget")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerStorageTarget indicates an expected call of GetContainerStorageTarget.
func (mr *MockOpsMockRecorder) GetContainerStorageTarget() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerStorageTarget", reflect.TypeOf((*MockOps)(nil).GetContainerStorageTarget))
}

// GetHostname mocks base method.
func (m *MockOps) GetHostname() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostname")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostname indicates an expected call of GetHostname.
func (mr *MockOpsMockRecorder) GetHostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostname", reflect.TypeOf((*MockOps)(nil).GetHostname))
}

// ImageExists mocks base method.
func (m *MockOps) ImageExists(img string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageExists", img)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageExists indicates an expected call of ImageExists.
func (mr *MockOpsMockRecorder) ImageExists(img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageExists", reflect.TypeOf((*MockOps)(nil).ImageExists), img)
}

// IsImageMounted mocks base method.
func (m *MockOps) IsImageMounted(img string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsImageMounted", img)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsImageMounted indicates an expected call of IsImageMounted.
func (mr *MockOpsMockRecorder) IsImageMounted(img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsImageMounted", reflect.TypeOf((*MockOps)(nil).IsImageMounted), img)
}

// IsNotExist mocks base method.
func (m *MockOps) IsNotExist(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNotExist", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNotExist indicates an expected call of IsNotExist.
func (mr *MockOpsMockRecorder) IsNotExist(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNotExist", reflect.TypeOf((*MockOps)(nil).IsNotExist), err)
}

// ListBlockDevices mocks base method.
func (m *MockOps) ListBlockDevices() ([]BlockDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlockDevices")
	ret0, _ := ret[0].([]BlockDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockDevices indicates an expected call of ListBlockDevices.
func (mr *MockOpsMockRecorder) ListBlockDevices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockDevices", reflect.TypeOf((*MockOps)(nil).ListBlockDevices))
}

// MkdirAll mocks base method.
func (m *MockOps) MkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockOpsMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockOps)(nil).MkdirAll), path, perm)
}

// Mount mocks base method.
func (m *MockOps) Mount(deviceName, mountFolder string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mount", deviceName, mountFolder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mount indicates an expected call of Mount.
func (mr *MockOpsMockRecorder) Mount(deviceName, mountFolder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mount", reflect.TypeOf((*MockOps)(nil).Mount), deviceName, mountFolder)
}

// MountImage mocks base method.
func (m *MockOps) MountImage(img string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MountImage", img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MountImage indicates an expected call of MountImage.
func (mr *MockOpsMockRecorder) MountImage(img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MountImage", reflect.TypeOf((*MockOps)(nil).MountImage), img)
}

// ReadDir mocks base method.
func (m *MockOps) ReadDir(path string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", path)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockOpsMockRecorder) ReadDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockOps)(nil).ReadDir), path)
}

// ReadFile mocks base method.
func (m *MockOps) ReadFile(filename string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", filename)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockOpsMockRecorder) ReadFile(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockOps)(nil).ReadFile), filename)
}

// RecertFullFlow mocks base method.
func (m *MockOps) RecertFullFlow(recertContainerImage, authFile, configFile string, preRecertOperations, postRecertOperations func() error, additionalPodmanParams ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{recertContainerImage, authFile, configFile, preRecertOperations, postRecertOperations}
	for _, a := range additionalPodmanParams {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RecertFullFlow", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecertFullFlow indicates an expected call of RecertFullFlow.
func (mr *MockOpsMockRecorder) RecertFullFlow(recertContainerImage, authFile, configFile, preRecertOperations, postRecertOperations any, additionalPodmanParams ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{recertContainerImage, authFile, configFile, preRecertOperations, postRecertOperations}, additionalPodmanParams...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecertFullFlow", reflect.TypeOf((*MockOps)(nil).RecertFullFlow), varargs...)
}

// RemountBoot mocks base method.
func (m *MockOps) RemountBoot() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemountBoot")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemountBoot indicates an expected call of RemountBoot.
func (mr *MockOpsMockRecorder) RemountBoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemountBoot", reflect.TypeOf((*MockOps)(nil).RemountBoot))
}

// RemountSysroot mocks base method.
func (m *MockOps) RemountSysroot() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemountSysroot")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemountSysroot indicates an expected call of RemountSysroot.
func (mr *MockOpsMockRecorder) RemountSysroot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemountSysroot", reflect.TypeOf((*MockOps)(nil).RemountSysroot))
}

// RemoveAllFiles mocks base method.
func (m *MockOps) RemoveAllFiles(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllFiles", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllFiles indicates an expected call of RemoveAllFiles.
func (mr *MockOpsMockRecorder) RemoveAllFiles(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllFiles", reflect.TypeOf((*MockOps)(nil).RemoveAllFiles), path)
}

// RemoveFile mocks base method.
func (m *MockOps) RemoveFile(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockOpsMockRecorder) RemoveFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockOps)(nil).RemoveFile), path)
}

// RestoreOriginalSeedCrypto mocks base method.
func (m *MockOps) RestoreOriginalSeedCrypto(recertContainerImage, authFile string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreOriginalSeedCrypto", recertContainerImage, authFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreOriginalSeedCrypto indicates an expected call of RestoreOriginalSeedCrypto.
func (mr *MockOpsMockRecorder) RestoreOriginalSeedCrypto(recertContainerImage, authFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreOriginalSeedCrypto", reflect.TypeOf((*MockOps)(nil).RestoreOriginalSeedCrypto), recertContainerImage, authFile)
}

// RunBashInHostNamespace mocks base method.
func (m *MockOps) RunBashInHostNamespace(command string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunBashInHostNamespace", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunBashInHostNamespace indicates an expected call of RunBashInHostNamespace.
func (mr *MockOpsMockRecorder) RunBashInHostNamespace(command any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunBashInHostNamespace", reflect.TypeOf((*MockOps)(nil).RunBashInHostNamespace), varargs...)
}

// RunInHostNamespace mocks base method.
func (m *MockOps) RunInHostNamespace(command string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunInHostNamespace", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunInHostNamespace indicates an expected call of RunInHostNamespace.
func (mr *MockOpsMockRecorder) RunInHostNamespace(command any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInHostNamespace", reflect.TypeOf((*MockOps)(nil).RunInHostNamespace), varargs...)
}

// RunListOfCommands mocks base method.
func (m *MockOps) RunListOfCommands(cmds []*CMD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunListOfCommands", cmds)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunListOfCommands indicates an expected call of RunListOfCommands.
func (mr *MockOpsMockRecorder) RunListOfCommands(cmds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunListOfCommands", reflect.TypeOf((*MockOps)(nil).RunListOfCommands), cmds)
}

// RunRecert mocks base method.
func (m *MockOps) RunRecert(recertContainerImage, authFile, recertConfigFile string, additionalPodmanParams ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{recertContainerImage, authFile, recertConfigFile}
	for _, a := range additionalPodmanParams {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunRecert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunRecert indicates an expected call of RunRecert.
func (mr *MockOpsMockRecorder) RunRecert(recertContainerImage, authFile, recertConfigFile any, additionalPodmanParams ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{recertContainerImage, authFile, recertConfigFile}, additionalPodmanParams...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRecert", reflect.TypeOf((*MockOps)(nil).RunRecert), varargs...)
}

// RunSystemdAction mocks base method.
func (m *MockOps) RunSystemdAction(args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunSystemdAction", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunSystemdAction indicates an expected call of RunSystemdAction.
func (mr *MockOpsMockRecorder) RunSystemdAction(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSystemdAction", reflect.TypeOf((*MockOps)(nil).RunSystemdAction), args...)
}

// RunUnauthenticatedEtcdServer mocks base method.
func (m *MockOps) RunUnauthenticatedEtcdServer(authFile, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunUnauthenticatedEtcdServer", authFile, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunUnauthenticatedEtcdServer indicates an expected call of RunUnauthenticatedEtcdServer.
func (mr *MockOpsMockRecorder) RunUnauthenticatedEtcdServer(authFile, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunUnauthenticatedEtcdServer", reflect.TypeOf((*MockOps)(nil).RunUnauthenticatedEtcdServer), authFile, name)
}

// SetupContainersFolderCommands mocks base method.
func (m *MockOps) SetupContainersFolderCommands() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupContainersFolderCommands")
	ret0, _ := ret[0].(error)
	return ret0
}

// SetupContainersFolderCommands indicates an expected call of SetupContainersFolderCommands.
func (mr *MockOpsMockRecorder) SetupContainersFolderCommands() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupContainersFolderCommands", reflect.TypeOf((*MockOps)(nil).SetupContainersFolderCommands))
}

// StatFile mocks base method.
func (m *MockOps) StatFile(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatFile", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatFile indicates an expected call of StatFile.
func (mr *MockOpsMockRecorder) StatFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatFile", reflect.TypeOf((*MockOps)(nil).StatFile), name)
}

// StopClusterServices mocks base method.
func (m *MockOps) StopClusterServices() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopClusterServices")
	ret0, _ := ret[0].(error)
	return ret0
}

// StopClusterServices indicates an expected call of StopClusterServices.
func (mr *MockOpsMockRecorder) StopClusterServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopClusterServices", reflect.TypeOf((*MockOps)(nil).StopClusterServices))
}

// StopEtcdServer mocks base method.
func (m *MockOps) StopEtcdServer(authfile, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopEtcdServer", authfile, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopEtcdServer indicates an expected call of StopEtcdServer.
func (mr *MockOpsMockRecorder) StopEtcdServer(authfile, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopEtcdServer", reflect.TypeOf((*MockOps)(nil).StopEtcdServer), authfile, name)
}

// SystemctlAction mocks base method.
func (m *MockOps) SystemctlAction(action string, args ...string) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{action}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SystemctlAction", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemctlAction indicates an expected call of SystemctlAction.
func (mr *MockOpsMockRecorder) SystemctlAction(action any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{action}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemctlAction", reflect.TypeOf((*MockOps)(nil).SystemctlAction), varargs...)
}

// Umount mocks base method.
func (m *MockOps) Umount(deviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Umount", deviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Umount indicates an expected call of Umount.
func (mr *MockOpsMockRecorder) Umount(deviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Umount", reflect.TypeOf((*MockOps)(nil).Umount), deviceName)
}

// UnmountAndRemoveImage mocks base method.
func (m *MockOps) UnmountAndRemoveImage(img string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmountAndRemoveImage", img)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmountAndRemoveImage indicates an expected call of UnmountAndRemoveImage.
func (mr *MockOpsMockRecorder) UnmountAndRemoveImage(img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmountAndRemoveImage", reflect.TypeOf((*MockOps)(nil).UnmountAndRemoveImage), img)
}

// WriteFile mocks base method.
func (m *MockOps) WriteFile(filename string, data []byte, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", filename, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockOpsMockRecorder) WriteFile(filename, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockOps)(nil).WriteFile), filename, data, perm)
}

// waitForEtcd mocks base method.
func (m *MockOps) waitForEtcd(healthzEndpoint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "waitForEtcd", healthzEndpoint)
	ret0, _ := ret[0].(error)
	return ret0
}

// waitForEtcd indicates an expected call of waitForEtcd.
func (mr *MockOpsMockRecorder) waitForEtcd(healthzEndpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "waitForEtcd", reflect.TypeOf((*MockOps)(nil).waitForEtcd), healthzEndpoint)
}
