# permissions for end users to view ImageBasedUpgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ImageBasedUpgrade-viewer-role
rules:
- apiGroups:
  - lca.openshift.io
  resources:
  - ImageBasedUpgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lca.openshift.io
  resources:
  - ImageBasedUpgrades/status
  verbs:
  - get
