# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile golang code
BUILDER_IMAGE=registry.redhat.io/openshift/golang-builder:golang-builder-v1.21-rhel9@sha256:d52999a7c2222c83ba488e5fb814a12d226c4b9e6de1c22abb647da7f552a028
#

# The openshift cli image is used to fetch the oc binary
OPENSHIFT_CLI_IMAGE=registry.redhat.io/openshift4/ose-cli-rhel9:v4.16@sha256:a746ed07c02f686c47248b3f3e6408067f47489a3578c9c592c4fd84a2a7da9e
#

# The opm image is used to serve the FBC
# There is a metadata processing bug preventing us from pinning this particular image for now
# OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.16@sha256:0415f8170633e05f6e108d8c06e3be5dbdfb0e1b4facbab6b624a4e0830f5ea4
#

# The runtime image is used to run the binaries
# This should match the dummy file Dockerfile.mintmaker in the lock-runtime directory
# Mintmaker should keep these in sync automatically when it performs updates
RUNTIME_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae
#

# The yq image is used at build time to manipulate yaml
YQ_IMAGE=quay.io/konflux-ci/yq:latest@sha256:9b73d39c362692d0bc5787c2b5e955cd54713e6bb97195a0fb2e87a6557040ee
#
