# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile golang code
# CNF-18555: When there is a Konflux build available for this then we need to update from the brew image
BUILDER_IMAGE=brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.25@sha256:c5d1bbc9c6ba9403017a30c2c71e9e28c9f43ffed2e60573a6de20e8ac753689
#

# The openshift cli image is used to fetch the oc binary
# When 4.21 is released, we need to update from the v4.20 tag
OPENSHIFT_CLI_IMAGE=registry.redhat.io/openshift4/ose-cli-rhel9:v4.20@sha256:18d9d46126acfe8ca89549d0e56c3b0c6fe978578dd8c57b2c131adff663df26
#

# The opm image is used to serve the FBC
# There is a metadata processing bug preventing us from pinning this particular image for now
# OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.22@sha256:ae8e121e6cd4da6af2ed85307771470cd65f5fcecb0fd5f04aae9fe931506c6b
#

# The runtime image is used to run the binaries
# This should match the dummy file Dockerfile.mintmaker in the lock-runtime directory
# Mintmaker should keep these in sync automatically when it performs updates
RUNTIME_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:062c52ff973065752b0965787649db2bcf551a6c727a00e95a3eb42cebadbdab
#

# The yq image is used at build time to manipulate yaml
YQ_IMAGE=quay.io/konflux-ci/yq:latest@sha256:e2b71e05fdb2a81fff75da6668c99d95da4a6c64224cc1262c9ee42348171fab
#
