# We can consume this arg to check whether a build is in Konflux or not
KONFLUX=true
#

# The builder image is used to compile golang code
# CNF-18555: When there is a Konflux build available for this then we need to update from the brew image
BUILDER_IMAGE=registry.redhat.io/openshift/golang-builder:golang-builder-v1.26-rhel9@sha256:036022b8a9057a8cf5b09ba9fd8519ca86ffbebde5501f366d9156f8cec01b1d
#

# The openshift cli image is used to fetch the oc binary
# When 4.21 is released, we need to update from the v4.20 tag
OPENSHIFT_CLI_IMAGE=registry.redhat.io/openshift4/ose-cli-rhel9:v4.20@sha256:278b945ba13b1d02b65752e86b6999fa5afcb55d2d39dc4f42ebdb19efbc969a
#

# The opm image is used to serve the FBC
# There is a metadata processing bug preventing us from pinning this particular image for now
# OPM_IMAGE=registry.redhat.io/openshift5/ose-operator-registry-rhel9:v5.0@sha256:bd914d872e4a082a61dbd502ef2069fdd23d401c37bc6457cbf81e77078155b5
#

# The runtime image is used to run the binaries
# This should match the dummy file Dockerfile.mintmaker in the lock-runtime directory
# Mintmaker should keep these in sync automatically when it performs updates
RUNTIME_IMAGE=registry.redhat.io/ubi9/ubi-minimal-pqc:latest@sha256:d34666200b64d5a183c867487fd2f48ee8547eb18134e5647099970e26f08af9
#

# The yq image is used at build time to manipulate yaml
YQ_IMAGE=quay.io/konflux-ci/yq:latest@sha256:9b73d39c362692d0bc5787c2b5e955cd54713e6bb97195a0fb2e87a6557040ee
#
