# Build the catalog
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.24@sha256:8412323224878c4e27cd6f7dc6ce99c50f878f37df323285bff29a53f8ec37cd AS builder

# create dir structure to generate the catalog
RUN mkdir -p /app/hack /app/.konflux/catalog
COPY Makefile /app
COPY .konflux/catalog/ /app/.konflux/catalog/
COPY telco5g-konflux /app/telco5g-konflux

# we need to copy the vendor/ folder as the Makefile depends on it
COPY vendor/ /app/vendor/

# generate the catalog

# debug
RUN echo "root dir" && ls -lra $HOME

WORKDIR /app
RUN --mount=type=secret,id=telco-5g-redhat-pull-secret/.dockerconfigjson \
    mkdir -p $HOME/.docker/ && \
    cp /run/secrets/telco-5g-redhat-pull-secret/.dockerconfigjson $HOME/.docker/config.json

# debug
RUN echo "run secrets" && ls -lra /run/secrets/ && echo "docker dir" && ls -lra $HOME/.docker/ && cat $HOME/.docker/config.json

ENV REGISTRY_AUTH_FILE=$HOME/.docker/config.json

# The Konflux build is not hermetic so it will download the tools (opm, yq, etc) automatically
# Konflux will externally sync the submodules so we can skip it here
RUN SKIP_SUBMODULE_SYNC=yes make konflux-generate-catalog-production && \
    rm -f $HOME/.docker/config.json

# Run the catalog
# Due to a Konflux limitation, we cannot use a pinned digest for this image.
FROM registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.21

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

# ensure this correponds to olm.package name
ENV PACKAGE_NAME=lifecycle-agent

COPY --from=builder /app/.konflux/catalog/$PACKAGE_NAME/ /configs/$PACKAGE_NAME
# RUN ["/bin/opm", "validate", "/configs/lifecycle-agent"]
RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

LABEL operators.operatorframework.io.index.configs.v1=/configs
