// Code generated by MockGen. DO NOT EDIT.
// Source: reboot.go
//
// Generated by this command:
//
//	mockgen -source=reboot.go -package=reboot -destination=mock_reboot.go
//
// Package reboot is a generated GoMock package.
package reboot

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRebootIntf is a mock of RebootIntf interface.
type MockRebootIntf struct {
	ctrl     *gomock.Controller
	recorder *MockRebootIntfMockRecorder
}

// MockRebootIntfMockRecorder is the mock recorder for MockRebootIntf.
type MockRebootIntfMockRecorder struct {
	mock *MockRebootIntf
}

// NewMockRebootIntf creates a new mock instance.
func NewMockRebootIntf(ctrl *gomock.Controller) *MockRebootIntf {
	mock := &MockRebootIntf{ctrl: ctrl}
	mock.recorder = &MockRebootIntfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRebootIntf) EXPECT() *MockRebootIntfMockRecorder {
	return m.recorder
}

// AutoRollbackIfEnabled mocks base method.
func (m *MockRebootIntf) AutoRollbackIfEnabled(ctx context.Context, component, msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AutoRollbackIfEnabled", ctx, component, msg)
}

// AutoRollbackIfEnabled indicates an expected call of AutoRollbackIfEnabled.
func (mr *MockRebootIntfMockRecorder) AutoRollbackIfEnabled(ctx, component, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoRollbackIfEnabled", reflect.TypeOf((*MockRebootIntf)(nil).AutoRollbackIfEnabled), ctx, component, msg)
}

// DisableInitMonitor mocks base method.
func (m *MockRebootIntf) DisableInitMonitor(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableInitMonitor", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableInitMonitor indicates an expected call of DisableInitMonitor.
func (mr *MockRebootIntfMockRecorder) DisableInitMonitor(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableInitMonitor", reflect.TypeOf((*MockRebootIntf)(nil).DisableInitMonitor), ctx)
}

// InitiateRollback mocks base method.
func (m *MockRebootIntf) InitiateRollback(ctx context.Context, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateRollback", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateRollback indicates an expected call of InitiateRollback.
func (mr *MockRebootIntfMockRecorder) InitiateRollback(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateRollback", reflect.TypeOf((*MockRebootIntf)(nil).InitiateRollback), ctx, msg)
}

// IsOrigStaterootBooted mocks base method.
func (m *MockRebootIntf) IsOrigStaterootBooted(ctx context.Context, identifier string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOrigStaterootBooted", ctx, identifier)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOrigStaterootBooted indicates an expected call of IsOrigStaterootBooted.
func (mr *MockRebootIntfMockRecorder) IsOrigStaterootBooted(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOrigStaterootBooted", reflect.TypeOf((*MockRebootIntf)(nil).IsOrigStaterootBooted), ctx, identifier)
}

// ReadAutoRollbackConfigFile mocks base method.
func (m *MockRebootIntf) ReadAutoRollbackConfigFile() (*AutoRollbackConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAutoRollbackConfigFile")
	ret0, _ := ret[0].(*AutoRollbackConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAutoRollbackConfigFile indicates an expected call of ReadAutoRollbackConfigFile.
func (mr *MockRebootIntfMockRecorder) ReadAutoRollbackConfigFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAutoRollbackConfigFile", reflect.TypeOf((*MockRebootIntf)(nil).ReadAutoRollbackConfigFile))
}

// Reboot mocks base method.
func (m *MockRebootIntf) Reboot(ctx context.Context, rationale string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx, rationale)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reboot indicates an expected call of Reboot.
func (mr *MockRebootIntfMockRecorder) Reboot(ctx, rationale any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockRebootIntf)(nil).Reboot), ctx, rationale)
}

// RebootToNewStateRoot mocks base method.
func (m *MockRebootIntf) RebootToNewStateRoot(ctx context.Context, rationale string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebootToNewStateRoot", ctx, rationale)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebootToNewStateRoot indicates an expected call of RebootToNewStateRoot.
func (mr *MockRebootIntfMockRecorder) RebootToNewStateRoot(ctx, rationale any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootToNewStateRoot", reflect.TypeOf((*MockRebootIntf)(nil).RebootToNewStateRoot), ctx, rationale)
}
