apiVersion: ran.openshift.io/v1alpha1
kind: ImageBasedUpgrade
metadata:
  name: upgrade
spec:
  stage: Idle
  seedImageRef:
    version: 4.13.9
    image: quay.io/dpenney/upgbackup:oneimage-cnfdf01


