// Code generated by MockGen. DO NOT EDIT.
// Source: rpmostreeclient.go
//
// Generated by this command:
//
//	mockgen -source=rpmostreeclient.go -package=rpmostreeclient -destination=mock_rpmostreeclient.go
//
// Package rpmostreeclient is a generated GoMock package.
package rpmostreeclient

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// GetCurrentStaterootName mocks base method.
func (m *MockIClient) GetCurrentStaterootName() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentStaterootName")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentStaterootName indicates an expected call of GetCurrentStaterootName.
func (mr *MockIClientMockRecorder) GetCurrentStaterootName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentStaterootName", reflect.TypeOf((*MockIClient)(nil).GetCurrentStaterootName))
}

// GetDeploymentID mocks base method.
func (m *MockIClient) GetDeploymentID(osname string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentID", osname)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentID indicates an expected call of GetDeploymentID.
func (mr *MockIClientMockRecorder) GetDeploymentID(osname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentID", reflect.TypeOf((*MockIClient)(nil).GetDeploymentID), osname)
}

// GetDeploymentIndex mocks base method.
func (m *MockIClient) GetDeploymentIndex(osname string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentIndex", osname)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentIndex indicates an expected call of GetDeploymentIndex.
func (mr *MockIClientMockRecorder) GetDeploymentIndex(osname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentIndex", reflect.TypeOf((*MockIClient)(nil).GetDeploymentIndex), osname)
}

// GetUnbootedDeploymentIndex mocks base method.
func (m *MockIClient) GetUnbootedDeploymentIndex() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnbootedDeploymentIndex")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnbootedDeploymentIndex indicates an expected call of GetUnbootedDeploymentIndex.
func (mr *MockIClientMockRecorder) GetUnbootedDeploymentIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnbootedDeploymentIndex", reflect.TypeOf((*MockIClient)(nil).GetUnbootedDeploymentIndex))
}

// GetUnbootedStaterootName mocks base method.
func (m *MockIClient) GetUnbootedStaterootName() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnbootedStaterootName")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnbootedStaterootName indicates an expected call of GetUnbootedStaterootName.
func (mr *MockIClientMockRecorder) GetUnbootedStaterootName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnbootedStaterootName", reflect.TypeOf((*MockIClient)(nil).GetUnbootedStaterootName))
}

// IsStaterootBooted mocks base method.
func (m *MockIClient) IsStaterootBooted(stateroot string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStaterootBooted", stateroot)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsStaterootBooted indicates an expected call of IsStaterootBooted.
func (mr *MockIClientMockRecorder) IsStaterootBooted(stateroot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStaterootBooted", reflect.TypeOf((*MockIClient)(nil).IsStaterootBooted), stateroot)
}

// QueryStatus mocks base method.
func (m *MockIClient) QueryStatus() (*Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryStatus")
	ret0, _ := ret[0].(*Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryStatus indicates an expected call of QueryStatus.
func (mr *MockIClientMockRecorder) QueryStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryStatus", reflect.TypeOf((*MockIClient)(nil).QueryStatus))
}

// RpmOstreeCleanup mocks base method.
func (m *MockIClient) RpmOstreeCleanup() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RpmOstreeCleanup")
	ret0, _ := ret[0].(error)
	return ret0
}

// RpmOstreeCleanup indicates an expected call of RpmOstreeCleanup.
func (mr *MockIClientMockRecorder) RpmOstreeCleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RpmOstreeCleanup", reflect.TypeOf((*MockIClient)(nil).RpmOstreeCleanup))
}

// RpmOstreeVersion mocks base method.
func (m *MockIClient) RpmOstreeVersion() (*VersionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RpmOstreeVersion")
	ret0, _ := ret[0].(*VersionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RpmOstreeVersion indicates an expected call of RpmOstreeVersion.
func (mr *MockIClientMockRecorder) RpmOstreeVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RpmOstreeVersion", reflect.TypeOf((*MockIClient)(nil).RpmOstreeVersion))
}

// newCmd mocks base method.
func (m *MockIClient) newCmd(args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "newCmd", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// newCmd indicates an expected call of newCmd.
func (mr *MockIClientMockRecorder) newCmd(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "newCmd", reflect.TypeOf((*MockIClient)(nil).newCmd), args...)
}
