apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: lifecycle-agent-digest-mirror-set
spec:
  imageDigestMirrors:
  - mirrors:
    - registry.stage.redhat.io/openshift4/lifecycle-agent-rhel9-operator
    source: registry.redhat.io/openshift4/lifecycle-agent-rhel9-operator
  - mirrors:
    - registry.stage.redhat.io/openshift4/lifecycle-agent-operator-bundle
    source: registry.redhat.io/openshift4/lifecycle-agent-operator-bundle
  - mirrors:
    - registry.stage.redhat.io/openshift4/recert-rhel9
    source: registry.redhat.io/openshift4/recert-rhel9
