---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/lifecycle-agent?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "release-4.20" &&
      (
        '.konflux/container_build_args.conf'.pathChanged() ||
        '.tekton/build-pipeline.yaml'.pathChanged() ||
        '.tekton/lifecycle-agent-4-20-pull-request.yaml'.pathChanged() ||
        'api/***'.pathChanged() ||
        'config/***'.pathChanged() ||
        'controllers/***'.pathChanged() ||
        'Dockerfile'.pathChanged() ||
        'go.mod'.pathChanged() ||
        'go.sum'.pathChanged() ||
        'hack/***'.pathChanged() ||
        'internal/***'.pathChanged() ||
        'lca-cli'.pathChanged() ||
        'main/***'.pathChanged() ||
        'must-gather/***'.pathChanged() ||
        'pkg/***'.pathChanged() ||
        'telco5g-konflux'.pathChanged() ||
        'telco5g-konflux/***'.pathChanged() ||
        'utils/***'.pathChanged() ||
        'vendor/***'.pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: lifecycle-agent-4-20
    appstudio.openshift.io/component: lifecycle-agent-4-20
    pipelines.appstudio.openshift.io/type: build
  name: lifecycle-agent-4-20-on-pull-request
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/lifecycle-agent-4-20:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
    - name: dockerfile
      value: Dockerfile
    - name: build-args-file
      value: .konflux/container_build_args.conf
    - name: hermetic
      value: "true"
    - name: dev-package-managers
      value: "true"
    - name: prefetch-input
      value: '[{"type": "rpm", "path": ".konflux/lock-runtime"}, {"type": "gomod", "path": "."}]'
    - name: build-source-image
      value: "true"
    - name: skip-sast-coverity
      value: "true"
    - name: additional-tags
      value: []
    - name: additional-labels
      value:
        - name=openshift4/lifecycle-agent-rhel9-operator
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-lifecycle-agent-4-20
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
