// Code generated by MockGen. DO NOT EDIT.
// Source: ../common.go
//
// Generated by this command:
//
//	mockgen -source ../common.go -destination mock_backuprestore.go -write_generate_directive
//
// Package mock_backuprestore is a generated GoMock package.
package mock_backuprestore

import (
	context "context"
	reflect "reflect"

	v1 "github.com/openshift-kni/lifecycle-agent/api/imagebasedupgrade/v1"
	backuprestore "github.com/openshift-kni/lifecycle-agent/internal/backuprestore"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -source ../common.go -destination mock_backuprestore.go -write_generate_directive

// MockBackuperRestorer is a mock of BackuperRestorer interface.
type MockBackuperRestorer struct {
	ctrl     *gomock.Controller
	recorder *MockBackuperRestorerMockRecorder
}

// MockBackuperRestorerMockRecorder is the mock recorder for MockBackuperRestorer.
type MockBackuperRestorerMockRecorder struct {
	mock *MockBackuperRestorer
}

// NewMockBackuperRestorer creates a new mock instance.
func NewMockBackuperRestorer(ctrl *gomock.Controller) *MockBackuperRestorer {
	mock := &MockBackuperRestorer{ctrl: ctrl}
	mock.recorder = &MockBackuperRestorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackuperRestorer) EXPECT() *MockBackuperRestorerMockRecorder {
	return m.recorder
}

// CleanupBackups mocks base method.
func (m *MockBackuperRestorer) CleanupBackups(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupBackups", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupBackups indicates an expected call of CleanupBackups.
func (mr *MockBackuperRestorerMockRecorder) CleanupBackups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupBackups", reflect.TypeOf((*MockBackuperRestorer)(nil).CleanupBackups), ctx)
}

// PatchPVsReclaimPolicy mocks base method.
func (m *MockBackuperRestorer) PatchPVsReclaimPolicy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchPVsReclaimPolicy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchPVsReclaimPolicy indicates an expected call of PatchPVsReclaimPolicy.
func (mr *MockBackuperRestorerMockRecorder) PatchPVsReclaimPolicy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchPVsReclaimPolicy", reflect.TypeOf((*MockBackuperRestorer)(nil).PatchPVsReclaimPolicy), ctx)
}

// RestorePVsReclaimPolicy mocks base method.
func (m *MockBackuperRestorer) RestorePVsReclaimPolicy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestorePVsReclaimPolicy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestorePVsReclaimPolicy indicates an expected call of RestorePVsReclaimPolicy.
func (mr *MockBackuperRestorerMockRecorder) RestorePVsReclaimPolicy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestorePVsReclaimPolicy", reflect.TypeOf((*MockBackuperRestorer)(nil).RestorePVsReclaimPolicy), ctx)
}

// StartBackup mocks base method.
func (m *MockBackuperRestorer) StartBackup(ctx context.Context, content []v1.ConfigMapRef, targetDir string) (*backuprestore.BackupTracker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBackup", ctx, content, targetDir)
	ret0, _ := ret[0].(*backuprestore.BackupTracker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartBackup indicates an expected call of StartBackup.
func (mr *MockBackuperRestorerMockRecorder) StartBackup(ctx, content, targetDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBackup", reflect.TypeOf((*MockBackuperRestorer)(nil).StartBackup), ctx, content, targetDir)
}

// StartRestore mocks base method.
func (m *MockBackuperRestorer) StartRestore(ctx context.Context) (*backuprestore.RestoreTracker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRestore", ctx)
	ret0, _ := ret[0].(*backuprestore.RestoreTracker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartRestore indicates an expected call of StartRestore.
func (mr *MockBackuperRestorerMockRecorder) StartRestore(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRestore", reflect.TypeOf((*MockBackuperRestorer)(nil).StartRestore), ctx)
}

// ValidateBackupConfigmaps mocks base method.
func (m *MockBackuperRestorer) ValidateBackupConfigmaps(ctx context.Context, content []v1.ConfigMapRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateBackupConfigmaps", ctx, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateBackupConfigmaps indicates an expected call of ValidateBackupConfigmaps.
func (mr *MockBackuperRestorerMockRecorder) ValidateBackupConfigmaps(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateBackupConfigmaps", reflect.TypeOf((*MockBackuperRestorer)(nil).ValidateBackupConfigmaps), ctx, content)
}
