//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRollbackOnFailure) DeepCopyInto(out *AutoRollbackOnFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRollbackOnFailure.
func (in *AutoRollbackOnFailure) DeepCopy() *AutoRollbackOnFailure {
	if in == nil {
		return nil
	}
	out := new(AutoRollbackOnFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIPStatus) DeepCopyInto(out *ClusterIPStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIPStatus.
func (in *ClusterIPStatus) DeepCopy() *ClusterIPStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterIPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetworkStatus) DeepCopyInto(out *ClusterNetworkStatus) {
	*out = *in
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(ClusterIPStatus)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(ClusterIPStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetworkStatus.
func (in *ClusterNetworkStatus) DeepCopy() *ClusterNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostIPStatus) DeepCopyInto(out *HostIPStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostIPStatus.
func (in *HostIPStatus) DeepCopy() *HostIPStatus {
	if in == nil {
		return nil
	}
	out := new(HostIPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostNetworkStatus) DeepCopyInto(out *HostNetworkStatus) {
	*out = *in
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(HostIPStatus)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(HostIPStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostNetworkStatus.
func (in *HostNetworkStatus) DeepCopy() *HostNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(HostNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPConfig) DeepCopyInto(out *IPConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPConfig.
func (in *IPConfig) DeepCopy() *IPConfig {
	if in == nil {
		return nil
	}
	out := new(IPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPConfigList) DeepCopyInto(out *IPConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPConfigList.
func (in *IPConfigList) DeepCopy() *IPConfigList {
	if in == nil {
		return nil
	}
	out := new(IPConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPConfigSpec) DeepCopyInto(out *IPConfigSpec) {
	*out = *in
	if in.IPv4 != nil {
		in, out := &in.IPv4, &out.IPv4
		*out = new(IPv4Config)
		**out = **in
	}
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(IPv6Config)
		**out = **in
	}
	if in.VLAN != nil {
		in, out := &in.VLAN, &out.VLAN
		*out = new(VLANConfig)
		**out = **in
	}
	if in.AutoRollbackOnFailure != nil {
		in, out := &in.AutoRollbackOnFailure, &out.AutoRollbackOnFailure
		*out = new(AutoRollbackOnFailure)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPConfigSpec.
func (in *IPConfigSpec) DeepCopy() *IPConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IPConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPConfigStatus) DeepCopyInto(out *IPConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidNextStages != nil {
		in, out := &in.ValidNextStages, &out.ValidNextStages
		*out = make([]IPConfigStage, len(*in))
		copy(*out, *in)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]*IPHistory, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IPHistory)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPConfigStatus.
func (in *IPConfigStatus) DeepCopy() *IPConfigStatus {
	if in == nil {
		return nil
	}
	out := new(IPConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPHistory) DeepCopyInto(out *IPHistory) {
	*out = *in
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make([]*IPPhase, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IPPhase)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.CompletionTime.DeepCopyInto(&out.CompletionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPHistory.
func (in *IPHistory) DeepCopy() *IPHistory {
	if in == nil {
		return nil
	}
	out := new(IPHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPhase) DeepCopyInto(out *IPPhase) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.CompletionTime.DeepCopyInto(&out.CompletionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPhase.
func (in *IPPhase) DeepCopy() *IPPhase {
	if in == nil {
		return nil
	}
	out := new(IPPhase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4Config) DeepCopyInto(out *IPv4Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4Config.
func (in *IPv4Config) DeepCopy() *IPv4Config {
	if in == nil {
		return nil
	}
	out := new(IPv4Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv6Config) DeepCopyInto(out *IPv6Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv6Config.
func (in *IPv6Config) DeepCopy() *IPv6Config {
	if in == nil {
		return nil
	}
	out := new(IPv6Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(HostNetworkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterNetwork != nil {
		in, out := &in.ClusterNetwork, &out.ClusterNetwork
		*out = new(ClusterNetworkStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANConfig) DeepCopyInto(out *VLANConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANConfig.
func (in *VLANConfig) DeepCopy() *VLANConfig {
	if in == nil {
		return nil
	}
	out := new(VLANConfig)
	in.DeepCopyInto(out)
	return out
}
